name: anx0-beta

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Docker Registry
      run:
        docker login ${{secrets.ANX1_ENV_LIB_GITHUB_SECRET_ANX0_DOCKER_REGISTRY}} --username ${{secrets.ANX1_ENV_LIB_GITHUB_SECRET_ANX0_DOCKER_USERNAME}} --password ${{secrets.ANX1_ENV_LIB_GITHUB_SECRET_ANX0_DOCKER_PASSWORD}}

    - name: Build the Docker image
      run: docker compose build

    - name: Add tag Docker image
      run: docker tag ${{ github.head_ref }}

    - name: Push the Docker images
      run: docker compose push